#
# yaml file to install other bioinformatics tools via brew
#
# Part of the microgvl.ansible.filesystem role for the GVL project.

- name: Install extra brew items
  homebrew: name="{{ item }}"
  environment: "{{ linuxbrew_env }}"
  with-items:
    - trimmomatic
    - sratoolkit
    - figtree
    - vsearch
    - andi
    - kat
    - kent-tools
    - gingr
    - kallisto


#Install some extra R libraries
- name: Add some R packages.
  command: >
    Rscript --slave --no-save --no-restore-history -e "if (! ('{{ item }}' %in% installed.packages()[,'Package'])) { install.packages(pkgs='{{ item }}', repos=c('http://cran.ms.unimelb.edu.au/')); print('Added'); } else { print('Already installed'); }"
  register: r_result
  failed_when: "r_result.rc != 0 or 'had non-zero exit status' in r_result.stderr"
  changed_when: "'Added' in r_result.stdout"
  with_items:
    - ape
    - nesoni-r
    - DESeq2
    - edgeR
    - limma
  become: yes
  become_user: root

# Install extra python packages to linuxbrew python.
- name: Install some extra python packages to linuxbrew python.
  pip: name="{{ item }}"
  with_items:
    - numpy
    - biopython
    - htseq
    - khmer
    - click
    - nesoni
    - DendroPy
    - ncbi-genome-download
    - bioblend
  environment: "{{ linuxbrew_env }}"

# Install some python3 packages too!
- name: Install some python3 packages
  pip: name="{{ item }}" executable=pip3
  with_items:
    - numpy
    - circlator
    - matplotlib
  environment: "{{ linuxbrew_env }}"
